# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 967d330771ac6090c061aa7d28023185d2416cf1f1ad6b3cbb28c80178ff525450c7dd70afad57af0397f60147b2405ada7840dd3e1d3b1a6569d381324d625d

test:
  secret_key_base: 33a2257e2faa105024a599c05d25ac53162f034b1b1a7a783abb91363d7679115a4e3b23bacfe4af8e4ca5a165b80cbcccc44fd20d98568b8b44e42078eeb77e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
